'use client';
import {useState,useRef} from 'react';
import {enquirySchema} from '@/lib/enquiry';
import {deliverEnquiry,type PreparedDelivery} from '@/lib/form-submit';
import {services} from '@/lib/content';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export function ContactForm({ready}:{ready:boolean}){const[errors,setErrors]=useState<Record<string,string>>({});const[status,setStatus]=useState('');const[busy,setBusy]=useState(false);const[service,setService]=useState('unsure');const statusRef=useRef<HTMLDivElement>(null);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));values.service=service==='unsure'?'':service;const parsed=enquirySchema.safeParse(values);setErrors({});setStatus('');if(!parsed.success){const next:Record<string,string>={};for(const issue of parsed.error.issues)next[String(issue.path[0])]=issue.message;setErrors(next);const first=String(parsed.error.issues[0].path[0]);form.querySelector<HTMLElement>(`[name="${first}"]`)?.focus();return;}setBusy(true);try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data),signal:AbortSignal.timeout(20000)});const result=await response.json() as {fields?:Record<string,string[]>;error?:string;delivery?:PreparedDelivery};if(!response.ok){if(result.fields){const next:Record<string,string>={};for(const[k,v]of Object.entries(result.fields))next[k]=(v as string[])[0];setErrors(next)}setStatus(result.error||'Unable to send your request. Please try again later.');}else{if(!result.delivery)throw new Error('Missing delivery details');const delivery=await deliverEnquiry(result.delivery);setStatus(delivery.message);if(delivery.ok){form.reset();setService('unsure')}}}catch{setStatus('We could not confirm delivery. Your details are still here; please try again later.')}finally{setBusy(false);setTimeout(()=>statusRef.current?.focus(),0)}}
 const field=(name:string,label:string,type='text',required=false,autoComplete?:string,maxLength=150)=><div className="field"><label htmlFor={name}>{label}{required?' *':' (optional)'}</label><input id={name} name={name} type={type} required={required} autoComplete={autoComplete} maxLength={maxLength} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`${name}-error`:undefined}/>{errors[name]&&<span className="error" id={`${name}-error`}>{errors[name]}</span>}</div>;
 return <form onSubmit={submit} noValidate aria-label="Business enquiry"><h2>Tell me about your business.</h2><p>Share what you’re working on and where you’d like support. Fields marked * are required.</p>{!ready&&<p className="notice">Online enquiries are not connected yet. Requests cannot be delivered at the moment. Please return once the service is available.</p>}<div className="form-grid">{field('name','Full name','text',true,'name',100)}{field('email','Email address','email',true,'email',254)}{field('business','Business name','text',false,'organization')}{field('website','Website URL','url',false,'url',500)}<div className="field full"><label id="service-label">Service of interest (optional)</label><Select value={service} onValueChange={setService}><SelectTrigger aria-labelledby="service-label" className="service-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unsure">I’m not sure yet</SelectItem>{services.map(s=><SelectItem value={s.slug} key={s.slug}>{s.title}</SelectItem>)}</SelectContent></Select></div><div className="field full"><label htmlFor="message">Main business challenge or message *</label><textarea id="message" name="message" rows={5} required minLength={10} maxLength={5000} aria-invalid={!!errors.message} aria-describedby={errors.message?'message-error':undefined}/>{errors.message&&<span id="message-error" className="error">{errors.message}</span>}</div></div><div className="hp" aria-hidden="true"><label htmlFor="companyFax">Leave this field empty</label><input id="companyFax" name="companyFax" tabIndex={-1} autoComplete="off"/></div><p className="micro" style={{marginTop:20}}>Your details will be used to respond to your enquiry and arrange any consultation you request. FormSubmit processes this enquiry for email delivery. This form does not subscribe you to marketing emails. A request does not confirm an appointment.</p><button className="button" type="submit" disabled={busy}>{busy?'Sending your request…':'Send Consultation / Business Enquiry'}</button><div ref={statusRef} tabIndex={-1} role="status" aria-live="polite" className={status?'status':''}>{status}</div><noscript><p className="notice">JavaScript is needed to submit this form. Please use the business email if one is listed.</p></noscript></form>
}



