import Link from '@/components/link';
import {services,faqs,brand} from '@/lib/content';
import {posts} from '@/content/posts';
import {CTA} from './site';
import {ArticleCard} from './article-card';
export function HomeSections(){return <>
 <section className="section container"><div className="split"><div><p className="eyebrow">LESS GUESSWORK. MORE DIRECTION.</p><h2>Good at your business.<br/>Ready to get better at marketing?</h2><p>Running a business is already a full-time job. Your marketing should bring clarity, not another overwhelming to-do list.</p></div><ul className="ticks"><li>Hard to find online? Build a more discoverable presence.</li><li>Inconsistent enquiries? Connect your message to the right people.</li><li>Activity without sales? Improve the path from interest to action.</li><li>Short on time? Focus on the work that matters most.</li><li>Unsure about AI? Start with tools that solve an actual problem.</li></ul></div></section>
 <section className="section soft"><div className="container"><p className="eyebrow">HOW I CAN HELP</p><div className="section-top"><h2>The right support.<br/>At the right stage.</h2><p>Connected marketing services, shaped around your business—not a one-size-fits-all checklist.</p></div><div className="grid">{services.map(s=><article className="card" key={s.slug}><span className="icon" aria-hidden="true">{s.icon}</span><h3>{s.title}</h3><p>{s.short}</p><Link className="card-link" href={`/services#${s.slug}`} aria-label={`Explore ${s.title}`}>Explore service</Link></article>)}</div></div></section>
 <section className="section container"><div className="split"><div><p className="eyebrow">A THOUGHTFUL WAY TO GROW</p><h2>Your goals lead.<br/>The technology follows.</h2><p>AI can make marketing work more efficient. Human judgment makes it relevant. I bring the two together with a clear focus on your customers and your business.</p><Link className="text-link" href="/about">More about my approach</Link></div><ul className="ticks">{['Strategy customized to your business','Practical AI, with human review','Measurable goals and useful progress reviews','Clear communication without the jargon','Actionable recommendations you can use','Support that fits your time and resources'].map(x=><li key={x}>{x}</li>)}</ul></div></section>
 <section className="section soft"><div className="container"><p className="eyebrow">FROM CONVERSATION TO ACTION</p><h2>A clear next step. Then another.</h2><div className="steps">{[['Let’s talk','Book your free consultation and share what you want to improve.'],['Understand your business','Review your customers, goals, and current marketing together.'],['Build your plan','Receive a customized digital marketing plan with practical priorities.'],['Put it into action','Implement with your team or discuss optional ongoing support.']].map(([t,p],i)=><div key={t}><span className="step-num">0{i+1}</span><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
 <section className="section container"><div className="split consultation-layout"><div className="monogram consultation-photo"><img src="/office-consultation.png" alt="Professional consultation in an office" width={941} height={1672} loading="lazy"/><strong>{brand.initials}</strong><span>HUMAN INSIGHT. AI ADVANTAGE.</span></div><div><p className="eyebrow">THE PERSON BEHIND THE PLAN</p><h2>Marketing that starts<br/>with listening.</h2><p>{brand.bio}</p><p>I believe useful advice should leave you knowing what to do next—and why it matters.</p><Link className="text-link" href="/about">Get to know my approach</Link></div></div></section>
 <section className="section soft"><div className="container"><p className="eyebrow">IDEAS YOU CAN PUT TO WORK</p><div className="section-top"><h2>A little clarity for<br/>your next move.</h2><Link className="text-link" href="/blog">Explore the blog</Link></div><div className="grid article-grid">{posts.map((post,i)=><ArticleCard post={post} index={i} key={post.slug}/>)}</div></div></section>
 <section className="section container faq-layout"><div className="faq"><p className="eyebrow">BEFORE WE TALK</p><h2>A few questions, answered.</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><img className="faq-portrait" src="/office-coffee-portrait.png" alt="Office portrait holding a coffee mug" width={1086} height={1448} loading="lazy"/></section><CTA/>
 </>}

