'use client';
import Link from '@/components/link';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {brand,booking,offer} from '@/lib/content';
const nav=[['Home','/'],['About Me','/about'],['Services','/services'],['Blog','/blog'],['Contact','/contact']];
export function Header(){const path=usePathname();const[open,setOpen]=useState(false);return <header className="header"><div className="container nav"><Link className="brand" href="/" aria-label={`${brand.name} home`}><span className="brandmark">n<span>.</span></span><span>{brand.name}<span className="brand-sub">AI MARKETING & STRATEGY</span></span></Link><button className="menu" aria-expanded={open} aria-controls="navigation" onClick={()=>setOpen(!open)}> {open?'Close menu':'Menu'}</button><nav id="navigation" className={open?'navlinks open':'navlinks'} aria-label="Main navigation" onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);document.querySelector<HTMLButtonElement>('.menu')?.focus()}}}>{nav.map(([label,url])=><Link key={url} href={url} aria-current={(path===url||(url!=='/'&&path.startsWith(url)))?'page':undefined} onClick={()=>setOpen(false)}>{label}</Link>)}<Link className="button small" href={booking} onClick={()=>setOpen(false)}>Book a Free Consultation Call</Link></nav></div></header>}
export function CTA({label='Let’s find your next opportunity for growth.'}:{label?:string}){return <section className="container closing"><div><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>{label}</h2><p>{offer}</p></div><div><Link className="button" href={booking}>Book a Free Consultation Call</Link><p className="micro">Practical advice. A clear direction. No pressure.</p></div></section>}
export function Footer(){return <footer className="container footer"><div><Link href="/" className="footer-brand">{brand.name}</Link><p>Human insight. AI advantage.<br/>Marketing with a clear purpose.</p>{brand.email&&<a href={`mailto:${brand.email}`}>{brand.email}</a>}{brand.location&&<p>{brand.location}</p>}</div><nav aria-label="Footer navigation">{nav.map(([label,url])=><Link key={url} href={url}>{label}</Link>)}</nav>{brand.socials.length>0&&<nav aria-label="Social profiles">{brand.socials.map(s=><a href={s.url} key={s.url}>{s.label}</a>)}</nav>}<div className="footer-bottom"><span>© {new Date().getFullYear()} {brand.name}. All rights reserved.</span><span>Thoughtful marketing. Meaningful connections.</span></div></footer>}

