export const brand = {
 name:'Neupane Digital Service', initials:'ND', person:'', location:'', email:'digitalbiznep@gmail.com', bookingUrl:'', siteUrl:'https://www.neupaneb.com.np', socials:[] as {label:string;url:string}[],
 bio:'I help small and medium businesses grow their online presence with thoughtful strategy, useful AI tools, and marketing built around their customers. My goal is to make your next step clear, practical, and manageable.'
};
export const booking=brand.bookingUrl||'/contact#consultation';
export const offer='During your free consultation, I’ll analyze your business, identify opportunities for growth, and create a customized digital marketing plan you can start implementing immediately.';
export const services=[
 {slug:'strategy',title:'AI Marketing Strategy & Consulting',short:'A clear direction. A practical plan. The right tools for your business.',challenge:'Too many marketing options and no clear starting point.',activities:['Review your audience, goals, and current marketing','Prioritize opportunities around your time and budget','Create an actionable roadmap and identify useful AI workflows'],audience:'Owners who want a focused plan before investing more in marketing.',benefit:'Give your marketing a clear direction and make better-informed decisions.',icon:'◎'},
 {slug:'seo',title:'SEO & Content Marketing',short:'Help the right customers find you when they’re looking for answers.',challenge:'Your business is difficult to find online, or your content is not reaching relevant customers.',activities:['Review search visibility and website content','Map customer questions to useful topics','Develop page improvements and an editorial plan'],audience:'Businesses ready to build a more useful, discoverable online presence.',benefit:'Improve your chances of being found by people already interested in what you offer.',icon:'⌕'},
 {slug:'social',title:'Social Media Strategy & Management',short:'Show up consistently with content that gives people a reason to care.',challenge:'Posting takes time but lacks a consistent message or purpose.',activities:['Define content themes and a realistic publishing rhythm','Plan audience-focused posts and creative briefs','Review engagement and refine your content'],audience:'Businesses that need a manageable, consistent social presence.',benefit:'Build familiarity and make it easier for potential customers to connect with you.',icon:'✳'},
 {slug:'advertising',title:'Paid Advertising & Lead Generation',short:'Reach a relevant audience and turn interest into meaningful enquiries.',challenge:'Advertising spend is disconnected from the quality of your enquiries.',activities:['Clarify audience, offer, and campaign goals','Plan campaigns, creative tests, and landing pages','Review lead quality and spending against agreed measures'],audience:'Businesses with a clear offer and a budget to test paid channels.',benefit:'Learn which messages and audiences are most likely to generate relevant enquiries.',icon:'◉'},
 {slug:'email',title:'Email Marketing & Automation',short:'Follow up thoughtfully and nurture customer relationships over time.',challenge:'Interested customers slip away because follow-up is inconsistent.',activities:['Map enquiry and customer follow-up journeys','Create helpful email content and sequences','Review consent, segmentation, and performance'],audience:'Businesses with permission-based contacts and repeat customer opportunities.',benefit:'Keep your business relevant with timely, useful communication.',icon:'✉'},
 {slug:'conversion',title:'Website & Landing Page Optimization',short:'Make the journey from curious visitor to confident enquiry simpler.',challenge:'People visit your website but leave without taking the next step.',activities:['Review page clarity, mobile usability, and calls to action','Identify friction in forms and customer journeys','Prioritize improvements and plan useful tests'],audience:'Businesses with a website or campaigns that need a clearer path to enquiry.',benefit:'Help visitors understand your offer and take action with less friction.',icon:'◇'}
];
export const faqs=[
 ['Who are your services for?','Small and medium business owners who want a clearer online presence, more relevant enquiries, and a practical approach to marketing. Recommendations fit your goals, audience, resources, and starting point.'],
 ['What happens during the free consultation?',offer],
 ['Do I need to understand AI to work with you?','No. We start with your business and explain recommendations in plain English. AI is a supporting tool; you do not need technical knowledge to get started.'],
 ['Can you help if I already have a website or campaigns?','Yes. We can review what is already working, identify gaps, and prioritize improvements before introducing anything new.'],
 ['Can I implement the plan myself?','Yes. The plan is designed to be actionable. You can implement it yourself, work with your team, or discuss optional ongoing support.'],
 ['How do we measure progress?','We agree on measures that connect to your goals, such as relevant enquiries, conversion rates, search visibility, and lead quality. We review the starting point and progress together without promising specific results.']
];



