import assert from 'node:assert/strict';
import {handleEnquiry} from '../lib/enquiry.ts';
import {deliverEnquiry} from '../lib/form-submit.ts';
const valid={name:'Test Owner',email:'owner@example.com',business:'Test Business',website:'https://example.com',service:'strategy',message:'I would like a clearer marketing plan.',companyFax:''};
const env={CONTACT_TO_EMAIL:'owner@example.com',FORM_SITE_URL:'https://test.local'};
let n=0;
const req=(data=valid,extra={})=>new Request('https://test.local/api/contact',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://test.local','cf-connecting-ip':'test-'+n++,...extra},body:JSON.stringify(data)});
assert.equal((await handleEnquiry(req({...valid,email:'bad'}),env)).status,422);
assert.equal((await handleEnquiry(req({...valid,website:'javascript:alert(1)'}),env)).status,422);
assert.equal((await handleEnquiry(req({...valid,companyFax:'bot'}),env)).status,422);
assert.equal((await handleEnquiry(req(valid,{Origin:'https://other.local'}),env)).status,403);
assert.equal((await handleEnquiry(req({...valid,message:'a'.repeat(17000)}),env)).status,413);
assert.equal((await handleEnquiry(req(),{})).status,503);
const prepared=await handleEnquiry(req({...valid,recipient:'attacker@example.com'}),env);
assert.equal(prepared.status,200);
const body=await prepared.json();assert.equal(body.message,undefined);assert.equal(body.delivery.endpoint,'https://formsubmit.co/ajax/owner%40example.com');assert.equal(body.delivery.payload._replyto,valid.email);assert.equal(body.delivery.payload.message,valid.message);
let calls=0;
const mock=async(url,options)=>{calls++;assert.equal(url,body.delivery.endpoint);assert.equal(options.credentials,'omit');assert.equal(options.headers.Referer,undefined);assert.deepEqual(JSON.parse(options.body),body.delivery.payload);return Response.json({success:'true',message:'The form was submitted successfully.'})};
assert.equal((await deliverEnquiry(body.delivery,mock)).ok,true);assert.equal(calls,1);
assert.equal((await deliverEnquiry(body.delivery,async()=>Response.json({success:false}))).ok,false);
assert.equal((await deliverEnquiry(body.delivery,async()=>Response.json({success:'false'}))).ok,false);
assert.equal((await deliverEnquiry(body.delivery,async()=>Response.json({success:'true'},{status:502}))).ok,false);
assert.equal((await deliverEnquiry(body.delivery,async()=>Response.json({}))).ok,false);
assert.equal((await deliverEnquiry(body.delivery,async()=>Response.json(null))).ok,false);
const activation=await deliverEnquiry(body.delivery,async()=>Response.json({success:'false',message:'This form needs Activation.'}));assert.equal(activation.ok,false);assert.match(activation.message,/awaiting activation/);
assert.equal((await deliverEnquiry(body.delivery,async()=>new Response('<html>Unavailable</html>',{status:503}))).ok,false);
assert.equal((await deliverEnquiry(body.delivery,async()=>{throw new Error('Network failure')})).ok,false);
assert.equal((await deliverEnquiry({...body.delivery,endpoint:'https://example.com/steal'},mock)).ok,false);assert.equal(calls,1);
for(let i=0;i<5;i++)await handleEnquiry(req(valid,{'cf-connecting-ip':'rate-test'}),{});
assert.equal((await handleEnquiry(req(valid,{'cf-connecting-ip':'rate-test'}),{})).status,429);
console.log('Passed: server validation/rate limits, fixed recipient, preparation is not success, browser delivery payload, provider acceptance, rejection, activation, invalid responses and network failure. No emails were sent.');
